usr/lib/*/syncevolution/backends/providergoa.so
usr/lib/*/syncevolution/backends/provideroauth2.so
usr/lib/*/syncevolution/backends/syncdav.so
usr/lib/*/syncevolution/backends/syncfile.so
usr/lib/*/syncevolution/backends/syncpbap.so
usr/lib/*/syncevolution/backends/synckcalextended.so
usr/lib/*/syncevolution/backends/syncmaemocal.so
usr/lib/*/syncevolution/backends/syncqtcontacts.so
usr/lib/*/syncevolution/backends/syncsqlite.so
usr/lib/*/syncevolution/backends/syncxmlrpc.so

usr/libexec/syncevo-local-sync
